# Generated by Django 4.2 on 2023-06-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDFWORDConverter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='word_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='words/'),
        ),
    ]
