# Generated by Django 4.2 on 2023-06-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDFWORDConverter', '0002_alter_document_word_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='word_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
