# Generated by Django 4.0.1 on 2022-12-25 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addblog',
            name='dexc',
        ),
    ]
