# Generated by Django 4.0.1 on 2023-01-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_addblog_dexc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addblog',
            name='tags',
        ),
        migrations.AddField(
            model_name='addblog',
            name='tags',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
