# Generated by Django 4.0.1 on 2023-01-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_addblog_tags_addblog_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='addblog',
            name='somefield',
            field=models.ManyToManyField(to='blogs.SomeModel'),
        ),
    ]
