# Generated by Django 4.2.4 on 2023-08-21 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_somemodel_addblog_somefield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addblog',
            name='img',
        ),
        migrations.RemoveField(
            model_name='addblog',
            name='somefield',
        ),
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
