# Generated by Django 4.2.4 on 2023-09-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_remove_addblog_img_remove_addblog_somefield_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblog',
            name='author',
            field=models.CharField(default='Coding India', max_length=150),
        ),
    ]
