# Generated by Django 4.2.4 on 2023-11-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_addblog_img_alter_playlist_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='addblog',
            name='slug',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
