# Generated by Django 4.2.4 on 2023-12-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(unique=True)),
                ('short_key', models.CharField(max_length=20, unique=True)),
                ('on_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
