# Generated by Django 4.2.4 on 2023-12-28 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UrlShortner', '0003_rename_user_shortenedurl_foruser'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shortenedurl',
            unique_together={('long_url', 'foruser')},
        ),
    ]
