# Generated by Django 4.2.4 on 2023-12-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlShortner', '0004_alter_shortenedurl_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='long_url',
            field=models.URLField(),
        ),
    ]
