# Generated by Django 4.2 on 2023-05-07 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_contactus_servicesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.servicesmodel'),
        ),
    ]
