# Generated by Django 4.2.4 on 2023-11-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_contactus_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='name',
            new_name='fname',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='services',
        ),
        migrations.AddField(
            model_name='contactus',
            name='lname',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='phone',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
