# Generated by Django 4.2.4 on 2023-12-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_portfolio_contactus_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='skills',
            field=models.ManyToManyField(to='website.skillsused'),
        ),
    ]
