# Generated by Django 4.2.4 on 2023-12-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_skillsused_portfolio_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
