# Generated by Django 4.2.4 on 2023-12-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_portfolio_solution_portfolio_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='client',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='industry',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='service',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
