# Generated by Django 4.2.4 on 2023-12-12 23:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_portfolio_client_portfolio_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='Solution',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='challenge',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='impact',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
