# Generated by Django 4.2.4 on 2023-12-12 23:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_portfolio_conclusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='conclusion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
